framework:
  rate_limiter:
    login_ip:
      policy: 'sliding_window'
      limit: 10
      interval: '15 minutes'
      
    login_ip_username:
        policy: 'sliding_window'
        limit: 10
        interval: '15 minutes'    