<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260123175847 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE gallery_daily_view (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, view_date DATE NOT NULL, ip_hash VARCHAR(64) DEFAULT NULL, gallery_id INT NOT NULL, user_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_D517451D4E7AF8F ON gallery_daily_view (gallery_id)');
        $this->addSql('CREATE INDEX IDX_D517451DA76ED395 ON gallery_daily_view (user_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_gallery_user_day ON gallery_daily_view (gallery_id, user_id, view_date)');
        $this->addSql('CREATE UNIQUE INDEX uniq_gallery_ip_day ON gallery_daily_view (gallery_id, ip_hash, view_date)');
        $this->addSql('ALTER TABLE gallery_daily_view ADD CONSTRAINT FK_D517451D4E7AF8F FOREIGN KEY (gallery_id) REFERENCES gallery (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE gallery_daily_view ADD CONSTRAINT FK_D517451DA76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE gallery DROP views');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE gallery_daily_view DROP CONSTRAINT FK_D517451D4E7AF8F');
        $this->addSql('ALTER TABLE gallery_daily_view DROP CONSTRAINT FK_D517451DA76ED395');
        $this->addSql('DROP TABLE gallery_daily_view');
        $this->addSql('ALTER TABLE gallery ADD views INT DEFAULT NULL');
    }
}
