<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260109012217 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE activity_log (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, action VARCHAR(50) NOT NULL, entity_class VARCHAR(255) NOT NULL, entity_id INT NOT NULL, old_values JSON DEFAULT NULL, new_values JSON DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_connected_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_FD06F647F2063BA5 ON activity_log (user_connected_id)');
        $this->addSql('CREATE TABLE artist (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, firstname VARCHAR(255) NOT NULL, lastname VARCHAR(255) NOT NULL, born_at DATE NOT NULL, died_at DATE DEFAULT NULL, nationality VARCHAR(255) DEFAULT NULL, biography TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, is_confirm_create BOOLEAN NOT NULL, to_be_confirmed BOOLEAN NOT NULL, profile_picture_id INT DEFAULT NULL, created_by_id INT DEFAULT NULL, updated_by_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_1599687292E8AE2 ON artist (profile_picture_id)');
        $this->addSql('CREATE INDEX IDX_1599687B03A8386 ON artist (created_by_id)');
        $this->addSql('CREATE INDEX IDX_1599687896DBBDE ON artist (updated_by_id)');
        $this->addSql('CREATE TABLE artwork (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) NOT NULL, type VARCHAR(255) NOT NULL, style VARCHAR(255) NOT NULL, creation_date DATE NOT NULL, description TEXT NOT NULL, location VARCHAR(255) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, is_display BOOLEAN NOT NULL, is_confirm_create BOOLEAN NOT NULL, to_be_confirmed BOOLEAN NOT NULL, image_id INT DEFAULT NULL, artist_id INT NOT NULL, created_by_id INT DEFAULT NULL, updated_by_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_881FC5763DA5256D ON artwork (image_id)');
        $this->addSql('CREATE INDEX IDX_881FC576B7970CF8 ON artwork (artist_id)');
        $this->addSql('CREATE INDEX IDX_881FC576B03A8386 ON artwork (created_by_id)');
        $this->addSql('CREATE INDEX IDX_881FC576896DBBDE ON artwork (updated_by_id)');
        $this->addSql('CREATE TABLE artwork_daily_view (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, view_date DATE NOT NULL, ip_hash VARCHAR(64) DEFAULT NULL, artwork_id INT NOT NULL, user_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_A2160AF9DB8FFA4 ON artwork_daily_view (artwork_id)');
        $this->addSql('CREATE INDEX IDX_A2160AF9A76ED395 ON artwork_daily_view (user_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_artwork_user_day ON artwork_daily_view (artwork_id, user_id, view_date)');
        $this->addSql('CREATE UNIQUE INDEX uniq_artwork_ip_day ON artwork_daily_view (artwork_id, ip_hash, view_date)');
        $this->addSql('CREATE TABLE gallery (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, description VARCHAR(255) DEFAULT NULL, views INT DEFAULT NULL, is_public BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, cover_image_id INT DEFAULT NULL, created_by_id INT DEFAULT NULL, updated_by_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_472B783AE5A0E336 ON gallery (cover_image_id)');
        $this->addSql('CREATE INDEX IDX_472B783AB03A8386 ON gallery (created_by_id)');
        $this->addSql('CREATE INDEX IDX_472B783A896DBBDE ON gallery (updated_by_id)');
        $this->addSql('CREATE TABLE gallery_artwork (gallery_id INT NOT NULL, artwork_id INT NOT NULL, PRIMARY KEY (gallery_id, artwork_id))');
        $this->addSql('CREATE INDEX IDX_B065845E4E7AF8F ON gallery_artwork (gallery_id)');
        $this->addSql('CREATE INDEX IDX_B065845EDB8FFA4 ON gallery_artwork (artwork_id)');
        $this->addSql('CREATE TABLE media_object (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, file_path VARCHAR(255) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE password_reset_token (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(255) NOT NULL, token VARCHAR(255) NOT NULL, expires_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE rating (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, score DOUBLE PRECISION NOT NULL, comment TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, artwork_id INT NOT NULL, created_by_id INT DEFAULT NULL, updated_by_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_D8892622DB8FFA4 ON rating (artwork_id)');
        $this->addSql('CREATE INDEX IDX_D8892622B03A8386 ON rating (created_by_id)');
        $this->addSql('CREATE INDEX IDX_D8892622896DBBDE ON rating (updated_by_id)');
        $this->addSql('CREATE TABLE refresh_tokens (refresh_token VARCHAR(128) NOT NULL, username VARCHAR(255) NOT NULL, valid TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_9BACE7E1C74F2195 ON refresh_tokens (refresh_token)');
        $this->addSql('CREATE TABLE "user" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, username VARCHAR(255) NOT NULL, email VARCHAR(180) NOT NULL, roles JSONB NOT NULL, password VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, is_suspended BOOLEAN NOT NULL, profile_picture_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8D93D649F85E0677 ON "user" (username)');
        $this->addSql('CREATE INDEX IDX_8D93D649292E8AE2 ON "user" (profile_picture_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_IDENTIFIER_EMAIL ON "user" (email)');
        $this->addSql('CREATE TABLE user_login_log (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, ip_hash VARCHAR(64) NOT NULL, event VARCHAR(20) NOT NULL, user_agent VARCHAR(255) DEFAULT NULL, message VARCHAR(255) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_connected_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_F18D121BF2063BA5 ON user_login_log (user_connected_id)');
        $this->addSql('ALTER TABLE activity_log ADD CONSTRAINT FK_FD06F647F2063BA5 FOREIGN KEY (user_connected_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE artist ADD CONSTRAINT FK_1599687292E8AE2 FOREIGN KEY (profile_picture_id) REFERENCES media_object (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE artist ADD CONSTRAINT FK_1599687B03A8386 FOREIGN KEY (created_by_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE artist ADD CONSTRAINT FK_1599687896DBBDE FOREIGN KEY (updated_by_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE artwork ADD CONSTRAINT FK_881FC5763DA5256D FOREIGN KEY (image_id) REFERENCES media_object (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE artwork ADD CONSTRAINT FK_881FC576B7970CF8 FOREIGN KEY (artist_id) REFERENCES artist (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE artwork ADD CONSTRAINT FK_881FC576B03A8386 FOREIGN KEY (created_by_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE artwork ADD CONSTRAINT FK_881FC576896DBBDE FOREIGN KEY (updated_by_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE artwork_daily_view ADD CONSTRAINT FK_A2160AF9DB8FFA4 FOREIGN KEY (artwork_id) REFERENCES artwork (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE artwork_daily_view ADD CONSTRAINT FK_A2160AF9A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE gallery ADD CONSTRAINT FK_472B783AE5A0E336 FOREIGN KEY (cover_image_id) REFERENCES media_object (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE gallery ADD CONSTRAINT FK_472B783AB03A8386 FOREIGN KEY (created_by_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE gallery ADD CONSTRAINT FK_472B783A896DBBDE FOREIGN KEY (updated_by_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE gallery_artwork ADD CONSTRAINT FK_B065845E4E7AF8F FOREIGN KEY (gallery_id) REFERENCES gallery (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE gallery_artwork ADD CONSTRAINT FK_B065845EDB8FFA4 FOREIGN KEY (artwork_id) REFERENCES artwork (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE rating ADD CONSTRAINT FK_D8892622DB8FFA4 FOREIGN KEY (artwork_id) REFERENCES artwork (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE rating ADD CONSTRAINT FK_D8892622B03A8386 FOREIGN KEY (created_by_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE rating ADD CONSTRAINT FK_D8892622896DBBDE FOREIGN KEY (updated_by_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE "user" ADD CONSTRAINT FK_8D93D649292E8AE2 FOREIGN KEY (profile_picture_id) REFERENCES media_object (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE user_login_log ADD CONSTRAINT FK_F18D121BF2063BA5 FOREIGN KEY (user_connected_id) REFERENCES "user" (id) ON DELETE SET NULL NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE activity_log DROP CONSTRAINT FK_FD06F647F2063BA5');
        $this->addSql('ALTER TABLE artist DROP CONSTRAINT FK_1599687292E8AE2');
        $this->addSql('ALTER TABLE artist DROP CONSTRAINT FK_1599687B03A8386');
        $this->addSql('ALTER TABLE artist DROP CONSTRAINT FK_1599687896DBBDE');
        $this->addSql('ALTER TABLE artwork DROP CONSTRAINT FK_881FC5763DA5256D');
        $this->addSql('ALTER TABLE artwork DROP CONSTRAINT FK_881FC576B7970CF8');
        $this->addSql('ALTER TABLE artwork DROP CONSTRAINT FK_881FC576B03A8386');
        $this->addSql('ALTER TABLE artwork DROP CONSTRAINT FK_881FC576896DBBDE');
        $this->addSql('ALTER TABLE artwork_daily_view DROP CONSTRAINT FK_A2160AF9DB8FFA4');
        $this->addSql('ALTER TABLE artwork_daily_view DROP CONSTRAINT FK_A2160AF9A76ED395');
        $this->addSql('ALTER TABLE gallery DROP CONSTRAINT FK_472B783AE5A0E336');
        $this->addSql('ALTER TABLE gallery DROP CONSTRAINT FK_472B783AB03A8386');
        $this->addSql('ALTER TABLE gallery DROP CONSTRAINT FK_472B783A896DBBDE');
        $this->addSql('ALTER TABLE gallery_artwork DROP CONSTRAINT FK_B065845E4E7AF8F');
        $this->addSql('ALTER TABLE gallery_artwork DROP CONSTRAINT FK_B065845EDB8FFA4');
        $this->addSql('ALTER TABLE rating DROP CONSTRAINT FK_D8892622DB8FFA4');
        $this->addSql('ALTER TABLE rating DROP CONSTRAINT FK_D8892622B03A8386');
        $this->addSql('ALTER TABLE rating DROP CONSTRAINT FK_D8892622896DBBDE');
        $this->addSql('ALTER TABLE "user" DROP CONSTRAINT FK_8D93D649292E8AE2');
        $this->addSql('ALTER TABLE user_login_log DROP CONSTRAINT FK_F18D121BF2063BA5');
        $this->addSql('DROP TABLE activity_log');
        $this->addSql('DROP TABLE artist');
        $this->addSql('DROP TABLE artwork');
        $this->addSql('DROP TABLE artwork_daily_view');
        $this->addSql('DROP TABLE gallery');
        $this->addSql('DROP TABLE gallery_artwork');
        $this->addSql('DROP TABLE media_object');
        $this->addSql('DROP TABLE password_reset_token');
        $this->addSql('DROP TABLE rating');
        $this->addSql('DROP TABLE refresh_tokens');
        $this->addSql('DROP TABLE "user"');
        $this->addSql('DROP TABLE user_login_log');
    }
}
