<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260110003025 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE validation_decision (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, subject_type VARCHAR(255) NOT NULL, subject_id INT NOT NULL, status VARCHAR(255) NOT NULL, reason TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, decided_by_id INT NOT NULL, submitted_by_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_63051612E26B496B ON validation_decision (decided_by_id)');
        $this->addSql('CREATE INDEX IDX_6305161279F7D87D ON validation_decision (submitted_by_id)');
        $this->addSql('ALTER TABLE validation_decision ADD CONSTRAINT FK_63051612E26B496B FOREIGN KEY (decided_by_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE validation_decision ADD CONSTRAINT FK_6305161279F7D87D FOREIGN KEY (submitted_by_id) REFERENCES "user" (id) ON DELETE SET NULL NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE validation_decision DROP CONSTRAINT FK_63051612E26B496B');
        $this->addSql('ALTER TABLE validation_decision DROP CONSTRAINT FK_6305161279F7D87D');
        $this->addSql('DROP TABLE validation_decision');
    }
}
