<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20251219142855 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE activity_log (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, action VARCHAR(50) NOT NULL, entity_class VARCHAR(255) NOT NULL, entity_id INT NOT NULL, old_values JSON DEFAULT NULL, new_values JSON DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_connected_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_FD06F647F2063BA5 ON activity_log (user_connected_id)');
        $this->addSql('CREATE TABLE user_login_log (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, ip VARCHAR(255) NOT NULL, event VARCHAR(20) NOT NULL, user_agent VARCHAR(255) DEFAULT NULL, message VARCHAR(255) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_connected_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_F18D121BF2063BA5 ON user_login_log (user_connected_id)');
        $this->addSql('ALTER TABLE activity_log ADD CONSTRAINT FK_FD06F647F2063BA5 FOREIGN KEY (user_connected_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE user_login_log ADD CONSTRAINT FK_F18D121BF2063BA5 FOREIGN KEY (user_connected_id) REFERENCES "user" (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE activity_log DROP CONSTRAINT FK_FD06F647F2063BA5');
        $this->addSql('ALTER TABLE user_login_log DROP CONSTRAINT FK_F18D121BF2063BA5');
        $this->addSql('DROP TABLE activity_log');
        $this->addSql('DROP TABLE user_login_log');
    }
}
